### ISSUE TITLE
Compile Carthagenet

### ISSUE THREAD

**Issue by neocybereth** [tezoscommunity/FAQ#14]
Using your Compile_mainnet.md I'm attempting to compile Carthagenet. Whenever I get to the `./tezos-node identity generate` step I'm continually getting ` Invalid data directory version '0.0.1' (expected '0.0.4').` Have you guys seen this error before?

**Comment by fredcy** [comment]
Sounds like you have a ~/.tezos-node directory left over from a prior build. You might want to move that aside or delete it if you don't need it, and start fresh. If you *do* need it (because you want to keep using the chain data you built up) then you'll need to upgrade the data. I forget how that's done but can dig deeper if you need that.

**Comment by neocybereth** [comment]
That was exactly it, thank you @fredcy !

**Comment by neocybereth** [comment]
Man I've had so much trouble for so long with this and that did the trick.....so great! Much appreciated @fredcy ...Feels amazing to have a node up and running and be syncing from a snapshot!
